### ISSUE TITLE
Multiple declarations linking errors

### ISSUE THREAD

**Issue by dbp** [osa1/hslua#40] opened 2016-01-08 15:50 UTC
I'm not sure if this is an issue for hslua, but I'm not sure where else it would belong. I'm getting a whole pile if linking errors when trying to build hslua 0.4.1 with stack. The full trace is:

```
Run from outside a project, using implicit global project config
hslua-0.4.1: configure
hslua-0.4.1: build

--  While building package hslua-0.4.1 using:
      /home/ubuntu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.4.0-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/ubuntu/.stack/global-project/.stack-work/logs/hslua-0.4.1.log

    Configuring hslua-0.4.1...
    Building hslua-0.4.1...
    Preprocessing library hslua-0.4.1...
    [1 of 2] Compiling Scripting.Lua.Raw ( .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Scripting/Lua/Raw.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Scripting/Lua/Raw.o )
    [2 of 2] Compiling Scripting.Lua    ( .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Scripting/Lua.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Scripting/Lua.o )
    
    src/Scripting/Lua.hsc:16:1: Warning:
        The import of ‘Control.Applicative’ is redundant
          except perhaps to import instances from ‘Control.Applicative’
        To import instances alone, use: import Control.Applicative()
    /tmp/ghc25112_0/ghc_11.o:(.data+0x0): multiple definition of `__stginit_hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x0): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x0): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_callfunczq_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x0): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.text+0x18): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_callfunczq_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x18): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x8): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_callproczq_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x8): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.text+0x38): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_callproczq_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x38): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x10): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_luaimportzq_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x10): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.text+0x58): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_luaimportzq_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x58): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x18): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_luaimportargerror_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x18): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cie3_info':
    (.text+0xb8): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_luaimportargerror_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0xb8): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x20): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_push_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x20): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cieo_info':
    (.text+0x118): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_push_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x118): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x28): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_peek_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x28): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cieJ_info':
    (.text+0x178): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_peek_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x178): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x30): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_valuetype_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x30): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cif4_info':
    (.text+0x1d8): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_valuetype_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x1d8): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x38): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfstableZZC1ZZChsluazzuDAXOloNJurRCYy4KgxvZZZZeZZZZZZCScriptingzziLuaZZChsmethodzzuzzugc3_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x38): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x48): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_callfunc2_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x48): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cifp_info':
    (.text+0x238): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_callfunc2_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x238): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x50): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa9_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x50): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cifp_info':
    (.text+0x258): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa9_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x258): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x58): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueInt3_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x58): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cigt_info':
    (.text+0x4f0): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueInt3_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x4f0): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x60): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa6_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x60): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cihP_info':
    (.text+0x590): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa6_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x590): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x68): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueDouble1_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x68): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `ciiG_info':
    (.text+0x838): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueDouble1_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x838): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x70): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa8_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x70): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cik2_info':
    (.text+0x8d8): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa8_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x8d8): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x78): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueInt1_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x78): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cikT_info':
    (.text+0xb70): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueInt1_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0xb70): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x80): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa7_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x80): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cimf_info':
    (.text+0xc10): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa7_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0xc10): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x88): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueFunPtr1_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x88): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cin6_info':
    (.text+0xea8): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueFunPtr1_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0xea8): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x90): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa11_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x90): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cios_info':
    (.text+0xf48): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdwa11_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0xf48): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0x98): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValuePtr1_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0x98): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cipj_info':
    (.text+0x11e0): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValuePtr1_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x11e0): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0xa0): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_maybepeek1_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0xa0): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `ciqF_info':
    (.text+0x1280): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_maybepeek1_info'
    /tmp/ghc25112_0/ghc_11.o:(.text+0x1280): first defined here
    /tmp/ghc25112_0/ghc_11.o:(.data+0xa8): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueLuaState2_closure'
    /tmp/ghc25112_0/ghc_11.o:(.data+0xa8): first defined here
    /tmp/ghc25112_0/ghc_11.o: In function `cirn_info':
    (.text+0x1388): multiple definition of `hsluazuDAXOloNJurRCYy4KgxvZZeZZ_ScriptingziLua_zdfStackValueLuaState2_info'
    /tmp/ghc25112_0/ghc_…
```

**Comment by limdauto** [comment] 2016-01-13 16:46
:+1:

**Comment by osa1** [comment] 2016-01-13 22:42
Sorry for the delay, I'll have a look at this today.

**Comment by osa1** [comment] 2016-01-14 16:55
I couldn't reproduce it. I'm using `Version 0.1.4.0, Git revision dac8cfe51802e08edb523b80c51cf35e21933513 (1722 commits) X86_64` on 64bit Linux. I think this may be a stack bug. What happens when you just do `cabal build`?

**Comment by limdauto** [comment] 2016-01-14 19:21
I'm using `cabal` actually. hslua is a dependency of hakyll and it couldn't be built by my CI machine, which is also running 64bit Linux.

<img width="1218" alt="screen shot 2016-01-14 at 7 20 03 pm" src="https://cloud.githubusercontent.com/assets/2032984/12334798/e1a8db22-baf3-11e5-8fa0-36fb9ceffa20.png">

**Comment by osa1** [comment] 2016-01-14 19:25
Could you tell me:

1. What version of Cabal and GHC are you using
2. Output of `cabal install -v`

**Comment by limdauto** [comment] 2016-01-14 22:29
Thank you for looking into it.

1. Cabal 1.22.6.0 && GHC 7.10.1
2. Output of `cabal install -v`

[output.txt](https://github.com/osa1/hslua/files/91093/output.txt)

**Comment by osa1** [comment] 2016-01-15 04:01
Hm. So I installed the same version of GHC, and my Cabal version is same too, and it seems like on my system Cabal is running exactly the same GHC command that it's running on your system. But for some reason it's working fine here.

What happens if you install Lua system-wide (with headers, if you're installing it using your distro's package manager) and do `cabal install -fsystem-lua` ?

**Comment by osa1** [comment] 2016-01-15 04:02
Actually, here's one more thing. Can you attach the output of `cabal install -v --ghc-options=-v` ?

**Comment by Yuras** [comment] 2016-01-15 13:13
It occurs because of `gcc-4.9.2`, see here: http://stackoverflow.com/questions/34654262/build-fails-because-of-multiple-definition-linker-errors-in-native-dependencie/34811594#34811594

**Comment by osa1** [comment] 2016-01-15 13:17
Interesting. So is this a gcc bug? @Yuras do you know if they have a bug report?

**Comment by Yuras** [comment] 2016-01-15 14:39
I didn't find a bug report, but it definitely looks like a bug in `gcc-4.9.2`. Though I'm not able to replicate it with `gcc-4.9.3`, so it seems to be already fixed.

**Comment by osa1** [comment] 2016-01-15 15:04
Thanks @Yuras for the investigation. I'm closing this.

**Closed by osa1** 2016-01-15 15:04 UTC

**Comment by dbp** [comment] 2016-01-15 16:35
Thanks @limdauto @osa1 and especially @Yuras!
