### ISSUE TITLE
HsLua directly calls Lua API functions that may throw errors

### ISSUE THREAD

**Issue by DemiMarie** [osa1/hslua#43] opened 2016-03-23 14:58 UTC
HsLua directly calls Lua API functions that may throw errors.  These need to be called via C wrappers or `lua_cpcall`.

**Comment by osa1** [comment] 2016-03-23 18:28
Which functions are those? Would you be willing to send a patch?

**Comment by drbo** [comment] 2016-03-24 23:22
The following functions/macros can throw an error due to memory exhaustion:

- `lua_checkstack`
- `lua_createtable`
- `lua_dump`
- `lua_newtable`
- `lua_newthread`
- `lua_newuserdata`
- `lua_pushcclosure`
- `lua_pushcfunction`
- `lua_pushfstring`
- `lua_pushliteral`
- `lua_pushlstring`
- `lua_pushstring`
- `lua_pushvfstring`
- `lua_rawset`
- `lua_rawseti`
- `lua_tolstring`
- `lua_tostring`
- `lua_getinfo`
- `luaL_addchar`
- `luaL_addlstring`
- `luaL_addsize`
- `luaL_addstring`
- `luaL_addvalue`
- `luaL_dofile`
- `luaL_dostring`
- `luaL_getmetafield`
- `luaL_gsub`
- `luaL_loadbuffer`
- `luaL_loadfile`
- `luaL_loadstring`
- `luaL_newmetatable`
- `luaL_openlibs`
- `luaL_pushresult`
- `luaL_ref`
- `luaL_register`
- `luaL_where`

The following functions/macros can throw errors for other reasons:

- `lua_call`
- `lua_concat`
- `lua_equal`
- `lua_gc`
- `lua_getfield`
- `lua_getglobal`
- `lua_gettable`
- `lua_lessthan`
- `lua_next`
- `lua_register`
- `lua_setfield`
- `lua_setglobal`
- `lua_settable`
- `luaL_callmeta`

The following functions/macros throw errors intentionally:

- `lua_error`
- `luaL_argcheck`
- `luaL_argerror`
- All of the `luaL_check*` functions
- `luaL_error`
- All of the `luaL_opt*` functions
- `luaL_typerror`

Finally, `lua_yield` should only be used as the last function called by a native-implemented Lua function (and indeed does a `longjmp` on Lua 5.2 and up).

While the GHC RTS generally aborts on memory exhaustion, I don't think that HsLua should always provide an allocator to Lua that does so, because limiting the memory usage of embedded scripts is a useful feature.

My solution to the problem of throwing Lua errors from Haskell is the following C function:

```c

typedef int (*HsLua_function)(lua_State *state, int upvals, int stackdepth);

typedef struct {
  HsLua_function func;
  int upvals;
} closure;

typedef struct {
   lua_State *state;
   HsLua_function self;
   int stackdepth;
   int stackused;
   int upvals;
} HsLua_State;

/**
 * Examines the return value of the Haskell function, throwing a Lua
 * error if it is negative.  This function cannot be safely written in
 * Haskell because the Lua error would skip over part of the Haskell
 * RTS.
 */
static int hslua_checkerror(lua_State *L) {
  closure haskell_closure = lua_touserdata(L, -1);
  lua_pop(L, 1);
  used = lua_gettop(L);
  HsLua_state state = {.state = L,
                       .self = haskell_closure->func,
                       .stackdepth = MAX(LUA_MINSTACK, used),
                       .stackused = used,
                       .upvals = haskell_closure->upvals};
  int number_of_return_values = haskell_closure->func(L, state);
  if (number_of_return_values >= 0) {
    /* Return normally */
    int top = lua_gettop(L);
    return number_of_return_values > top ? top : number_of_return_values
  } else if (number_of_return_values == INT_MIN) {
    /* Throw an error */
    lua_error(L);
  } else {
    /* Yield a coroutine */
    return lua_yield(L, number_of_return_values + 1)
  }
}
```
This allows for Haskell code to throw Lua errors or yield a Lua coroutine by returning a negative number.

The only solution to the problem of Lua functions that throw errors is to wrap them in C functions that catch the errors, and/or write higher-level C functions that can perform many operations under the scope of one `lua_pcall`.  For example, Haskell-implemented Lua functions could contain metadata that wrapper C code uses to extract arguments from Lua and push return values for Lua.  Other functions that may throw errors can be wrapped into higher-level C functions too.

I am willing to write a patch, but it will probably be large and complex, and I may not have time for a while.

This actually shows the greatest weakness of the Lua embedding API: since the API uses `longjmp` heavily, it is hard to call from other than C.

**Comment by osa1** [comment] 2016-03-27 16:32
@drbo, I don't have time and motivation to work on this right now. If you send a pull request with an explanation of the problem and your solution I'd be happy to merge (I'm actually looking for someone to take over maintainership of the package).

Note that we go great lengths to avoid this `longjmp` problem of Lua. See error handling examples in `examples/err_prop` and documentation about error handling in the main module. IIRC what I did to solve the problem is something like what you described.

**Comment by drbo** [comment] 2016-05-04 01:18
@osa1 I wrote [a library][1] that is designed to handle this problem (for all embedders).

[1]: /drbo/safer-lua-api

**Comment by tarleb** [comment] 2017-07-20 21:29
I did some experimenting with a lua-only approach, exemplified using a safe version of `lua_getfield`:

``` C
int hslua_getfield_closure(lua_State *L) {
  int index = lua_upvalueindex(1);
  const char *k = lua_tostring(L, lua_upvalueindex(2));
  lua_getfield(L, index, k);
  return 1;
}

int hslua_getfield(lua_State *L, int index, const char *k)
{
  lua_pushvalue(L, index);
  lua_pushlstring(L, k, strlen(k));
  lua_pushcclosure(L, hslua_getfield_closure, 2);
  return lua_pcall(L, 0, LUA_MULTRET, 0);
}
```

The advantage is that it still as portable as lua itself, the downside being that it requires a lot of boilerplate code to be written. Performance isn't affected much, the most expensive part is calling out to C from Haskell.

@DemiMarie, you put a lot of thought into this problem. Do you see this as a viable option?

**Comment by DemiMarie** [comment] 2017-07-21 12:12
I do.  I wrote a library to handle all of that boilerplate.  It's
surprisingly hard, since lua_pushcclosure can itself throw an error if Lua
runs out of memory, and one cannot just about in that case because one
might want to limit the amount of memory available to Lua.

My library is https://github.com/DemiMarie/safer-lua-api.

**Comment by tarleb** [comment] 2017-07-29 10:04
Thanks for your feedback @DemiMarie! The library looks very nice. I don't fully understand it yet, but it is a highly interesting read.
I used some custom wrappers for error-throwing functions for now. It was the simplest solution for me and doesn't complicate our build process. I'm open to include your library at a later point, as this would allow us to also handle memory allocation errors.
Closing this issue for now, as the worst problems should be solved.

**Closed by tarleb** 2017-07-29 10:04 UTC
